#
#
# This is a sample newrelic_plugin.yml file. Please move this file
# to the following location if it is not already there:
#
#     ./config/newrelic_plugin.yml
#
# Where the current directory is the directory where your main program resides and is your current
# directory when you run the main program.
#
# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'LICENSE_KEY'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 0
#
# Agent Configuration:
#
agents:
  riak_cs:
    host: HOSTNAME
    port: 8080
    access_id: 'ADMIN_KEY'
    secret_key: 'ADMIN_SECRET'
    cookie: 'ERLANG_COOKIE'
